# Generated by Django 4.2.16 on 2024-10-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_alter_basketitem_ticket_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
