# Generated by Django 4.2.16 on 2024-10-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_alter_basketitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='car_brand',
            new_name='car_make',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='max_entries_per_user',
        ),
        migrations.RemoveField(
            model_name='holidaycompetition',
            name='max_entries_per_user',
        ),
    ]
