# Generated by Django 4.2.16 on 2024-10-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_rename_car_brand_competition_car_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
