# Generated by Django 4.2.16 on 2024-11-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_alter_competition_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='index_display',
            field=models.BooleanField(default=False, help_text='Show on index page'),
        ),
        migrations.AddField(
            model_name='competition',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Priority 1'), (2, 'Priority 2'), (3, 'Priority 3'), (4, 'Priority 4')], help_text='Set priority from 1-4 for index page display order', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='holidaycompetition',
            name='index_display',
            field=models.BooleanField(default=False, help_text='Show on index page'),
        ),
        migrations.AddField(
            model_name='holidaycompetition',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Priority 1'), (2, 'Priority 2'), (3, 'Priority 3'), (4, 'Priority 4')], help_text='Set priority from 1-4 for index page display order', null=True, unique=True),
        ),
    ]
