# Generated by Django 4.2.16 on 2024-11-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0014_competition_index_display_competition_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='competition',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
