# Generated by Django 4.2.16 on 2024-11-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0015_alter_competition_options_competition_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={},
        ),
        migrations.RemoveField(
            model_name='competition',
            name='order',
        ),
    ]
